version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: veerrza_user
      POSTGRES_PASSWORD: veerrza_password
      POSTGRES_DB: veerrza_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veerrza_user -d veerrza_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build: .
    volumes:
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://veerrza_user:veerrza_password@db:5432/veerrza_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn veerrzastore.wsgi:application --bind 0.0.0.0:8000 --workers 2 --access-logfile - --error-logfile -
      "

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
    name: veerrza-network
